name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build --workspaces

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          # Publish the main package
          cd packages/locallytics
          npm version patch --no-git-tag-version
          npm publish --access public

          # Publish the CLI package
          cd ../cli
          npm version patch --no-git-tag-version
          npm publish --access public

          # Commit version changes
          cd ../..
          git add .
          git commit -m "chore: release new versions"
          git push
