name: Publish Packages

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["locallytics", "cli"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install and publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd packages/${{ matrix.package }}

          # Install dependencies (this will update package-lock.json if needed)
          npm install

          # Build the package
          npm run build --if-present

          # Publish with the current version
          npm publish --access public
