name: Publish Packages

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['locallytics', 'cli']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd packages/${{ matrix.package }}
          npm install -g npm@latest
          # First try npm ci, if it fails, fall back to npm install
          if ! npm ci; then
            echo "⚠️ package-lock.json out of sync with package.json, running npm install..."
            npm install
          fi
          
      - name: Build package
        run: |
          cd packages/${{ matrix.package }}
          npm run build --if-present
          
      - name: Publish package
        if: success()
        run: |
          cd packages/${{ matrix.package }}
          npm publish --access public
