name: Publish Packages

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - "packages/**/package.json"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g npm@latest

      - name: Build packages
        run: npm run build --workspaces

      - name: Publish @locallytics/cli
        working-directory: ./packages/cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public --registry=https://registry.npmjs.org/

      - name: Publish locallytics
        working-directory: ./packages/locallytics
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public --registry=https://registry.npmjs.org/

      - name: Commit version updates
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "chore(release): publish packages" && git push)
